kind: "Template"
apiVersion: "v1"
metadata:
  name: tomcat-template
  labels:
    template: "tomcat-template"
    app: "tomcat-template"
objects:
  - kind: Pod
    apiVersion: v1
    metadata:
      name: tomcat-pod
      labels:
        app: tomcat-pod
    namespace: dacpac
    spec: 
      containers:
      - name: tomcat-con
        image: raviteja101/new-tomcat
        ports:
          - containerPort: 8080
            protocol: TCP
        imagePullPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: tomcat-service
      labels:
        app: tomcat-service
        app.kubernetes.io/component: tomcat-new
        app.kubernetes.io/instance: tomcat-new
    namespace: dacpac
    spec:
      ports:
        - name: tomcat-port
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: tomcat-pod
      type: ClusterIP
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: tomcat-route
      labels:
        app: tomcat-route
        app.kubernetes.io/component: tomcat-new
        app.kubernetes.io/instance: tomcat-new
    spec:
      path: /jenkins
      to:
        kind: Service
        name: tomcat-service
      port:
        targetPort: 8080